/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as protecedRouteRouteImport } from './routes/(proteced)/route'
import { Route as protecedIndexRouteImport } from './routes/(proteced)/index'
import { Route as loginRegisterRouteImport } from './routes/(login)/register'
import { Route as loginLoginRouteImport } from './routes/(login)/login'
import { Route as protecedProfileIndexRouteImport } from './routes/(proteced)/profile/index'
import { Route as protecedOrdersIndexRouteImport } from './routes/(proteced)/orders/index'
import { Route as protecedMycartIndexRouteImport } from './routes/(proteced)/mycart/index'
import { Route as protecedAboutIndexRouteImport } from './routes/(proteced)/about/index'
import { Route as protecedStoresNewarrivalsRouteImport } from './routes/(proteced)/stores/newarrivals'
import { Route as protecedStoresTopSellRouteImport } from './routes/(proteced)/stores/TopSell'
import { Route as protecedStoresIdRouteImport } from './routes/(proteced)/stores/$id'
import { Route as protecedStoresTypeIdRouteImport } from './routes/(proteced)/stores/type/$id'
import { Route as protecedStoresProductIdRouteImport } from './routes/(proteced)/stores/product/$id'

const protecedRouteRoute = protecedRouteRouteImport.update({
  id: '/(proteced)',
  getParentRoute: () => rootRouteImport,
} as any)
const protecedIndexRoute = protecedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => protecedRouteRoute,
} as any)
const loginRegisterRoute = loginRegisterRouteImport.update({
  id: '/(login)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const loginLoginRoute = loginLoginRouteImport.update({
  id: '/(login)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const protecedProfileIndexRoute = protecedProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => protecedRouteRoute,
} as any)
const protecedOrdersIndexRoute = protecedOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => protecedRouteRoute,
} as any)
const protecedMycartIndexRoute = protecedMycartIndexRouteImport.update({
  id: '/mycart/',
  path: '/mycart/',
  getParentRoute: () => protecedRouteRoute,
} as any)
const protecedAboutIndexRoute = protecedAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => protecedRouteRoute,
} as any)
const protecedStoresNewarrivalsRoute =
  protecedStoresNewarrivalsRouteImport.update({
    id: '/stores/newarrivals',
    path: '/stores/newarrivals',
    getParentRoute: () => protecedRouteRoute,
  } as any)
const protecedStoresTopSellRoute = protecedStoresTopSellRouteImport.update({
  id: '/stores/TopSell',
  path: '/stores/TopSell',
  getParentRoute: () => protecedRouteRoute,
} as any)
const protecedStoresIdRoute = protecedStoresIdRouteImport.update({
  id: '/stores/$id',
  path: '/stores/$id',
  getParentRoute: () => protecedRouteRoute,
} as any)
const protecedStoresTypeIdRoute = protecedStoresTypeIdRouteImport.update({
  id: '/stores/type/$id',
  path: '/stores/type/$id',
  getParentRoute: () => protecedRouteRoute,
} as any)
const protecedStoresProductIdRoute = protecedStoresProductIdRouteImport.update({
  id: '/stores/product/$id',
  path: '/stores/product/$id',
  getParentRoute: () => protecedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof loginLoginRoute
  '/register': typeof loginRegisterRoute
  '/': typeof protecedIndexRoute
  '/stores/$id': typeof protecedStoresIdRoute
  '/stores/TopSell': typeof protecedStoresTopSellRoute
  '/stores/newarrivals': typeof protecedStoresNewarrivalsRoute
  '/about/': typeof protecedAboutIndexRoute
  '/mycart/': typeof protecedMycartIndexRoute
  '/orders/': typeof protecedOrdersIndexRoute
  '/profile/': typeof protecedProfileIndexRoute
  '/stores/product/$id': typeof protecedStoresProductIdRoute
  '/stores/type/$id': typeof protecedStoresTypeIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof loginLoginRoute
  '/register': typeof loginRegisterRoute
  '/': typeof protecedIndexRoute
  '/stores/$id': typeof protecedStoresIdRoute
  '/stores/TopSell': typeof protecedStoresTopSellRoute
  '/stores/newarrivals': typeof protecedStoresNewarrivalsRoute
  '/about': typeof protecedAboutIndexRoute
  '/mycart': typeof protecedMycartIndexRoute
  '/orders': typeof protecedOrdersIndexRoute
  '/profile': typeof protecedProfileIndexRoute
  '/stores/product/$id': typeof protecedStoresProductIdRoute
  '/stores/type/$id': typeof protecedStoresTypeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(proteced)': typeof protecedRouteRouteWithChildren
  '/(login)/login': typeof loginLoginRoute
  '/(login)/register': typeof loginRegisterRoute
  '/(proteced)/': typeof protecedIndexRoute
  '/(proteced)/stores/$id': typeof protecedStoresIdRoute
  '/(proteced)/stores/TopSell': typeof protecedStoresTopSellRoute
  '/(proteced)/stores/newarrivals': typeof protecedStoresNewarrivalsRoute
  '/(proteced)/about/': typeof protecedAboutIndexRoute
  '/(proteced)/mycart/': typeof protecedMycartIndexRoute
  '/(proteced)/orders/': typeof protecedOrdersIndexRoute
  '/(proteced)/profile/': typeof protecedProfileIndexRoute
  '/(proteced)/stores/product/$id': typeof protecedStoresProductIdRoute
  '/(proteced)/stores/type/$id': typeof protecedStoresTypeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/register'
    | '/'
    | '/stores/$id'
    | '/stores/TopSell'
    | '/stores/newarrivals'
    | '/about/'
    | '/mycart/'
    | '/orders/'
    | '/profile/'
    | '/stores/product/$id'
    | '/stores/type/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/'
    | '/stores/$id'
    | '/stores/TopSell'
    | '/stores/newarrivals'
    | '/about'
    | '/mycart'
    | '/orders'
    | '/profile'
    | '/stores/product/$id'
    | '/stores/type/$id'
  id:
    | '__root__'
    | '/(proteced)'
    | '/(login)/login'
    | '/(login)/register'
    | '/(proteced)/'
    | '/(proteced)/stores/$id'
    | '/(proteced)/stores/TopSell'
    | '/(proteced)/stores/newarrivals'
    | '/(proteced)/about/'
    | '/(proteced)/mycart/'
    | '/(proteced)/orders/'
    | '/(proteced)/profile/'
    | '/(proteced)/stores/product/$id'
    | '/(proteced)/stores/type/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  protecedRouteRoute: typeof protecedRouteRouteWithChildren
  loginLoginRoute: typeof loginLoginRoute
  loginRegisterRoute: typeof loginRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(proteced)': {
      id: '/(proteced)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protecedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(proteced)/': {
      id: '/(proteced)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof protecedIndexRouteImport
      parentRoute: typeof protecedRouteRoute
    }
    '/(login)/register': {
      id: '/(login)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof loginRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(login)/login': {
      id: '/(login)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof loginLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(proteced)/profile/': {
      id: '/(proteced)/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof protecedProfileIndexRouteImport
      parentRoute: typeof protecedRouteRoute
    }
    '/(proteced)/orders/': {
      id: '/(proteced)/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof protecedOrdersIndexRouteImport
      parentRoute: typeof protecedRouteRoute
    }
    '/(proteced)/mycart/': {
      id: '/(proteced)/mycart/'
      path: '/mycart'
      fullPath: '/mycart/'
      preLoaderRoute: typeof protecedMycartIndexRouteImport
      parentRoute: typeof protecedRouteRoute
    }
    '/(proteced)/about/': {
      id: '/(proteced)/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof protecedAboutIndexRouteImport
      parentRoute: typeof protecedRouteRoute
    }
    '/(proteced)/stores/newarrivals': {
      id: '/(proteced)/stores/newarrivals'
      path: '/stores/newarrivals'
      fullPath: '/stores/newarrivals'
      preLoaderRoute: typeof protecedStoresNewarrivalsRouteImport
      parentRoute: typeof protecedRouteRoute
    }
    '/(proteced)/stores/TopSell': {
      id: '/(proteced)/stores/TopSell'
      path: '/stores/TopSell'
      fullPath: '/stores/TopSell'
      preLoaderRoute: typeof protecedStoresTopSellRouteImport
      parentRoute: typeof protecedRouteRoute
    }
    '/(proteced)/stores/$id': {
      id: '/(proteced)/stores/$id'
      path: '/stores/$id'
      fullPath: '/stores/$id'
      preLoaderRoute: typeof protecedStoresIdRouteImport
      parentRoute: typeof protecedRouteRoute
    }
    '/(proteced)/stores/type/$id': {
      id: '/(proteced)/stores/type/$id'
      path: '/stores/type/$id'
      fullPath: '/stores/type/$id'
      preLoaderRoute: typeof protecedStoresTypeIdRouteImport
      parentRoute: typeof protecedRouteRoute
    }
    '/(proteced)/stores/product/$id': {
      id: '/(proteced)/stores/product/$id'
      path: '/stores/product/$id'
      fullPath: '/stores/product/$id'
      preLoaderRoute: typeof protecedStoresProductIdRouteImport
      parentRoute: typeof protecedRouteRoute
    }
  }
}

interface protecedRouteRouteChildren {
  protecedIndexRoute: typeof protecedIndexRoute
  protecedStoresIdRoute: typeof protecedStoresIdRoute
  protecedStoresTopSellRoute: typeof protecedStoresTopSellRoute
  protecedStoresNewarrivalsRoute: typeof protecedStoresNewarrivalsRoute
  protecedAboutIndexRoute: typeof protecedAboutIndexRoute
  protecedMycartIndexRoute: typeof protecedMycartIndexRoute
  protecedOrdersIndexRoute: typeof protecedOrdersIndexRoute
  protecedProfileIndexRoute: typeof protecedProfileIndexRoute
  protecedStoresProductIdRoute: typeof protecedStoresProductIdRoute
  protecedStoresTypeIdRoute: typeof protecedStoresTypeIdRoute
}

const protecedRouteRouteChildren: protecedRouteRouteChildren = {
  protecedIndexRoute: protecedIndexRoute,
  protecedStoresIdRoute: protecedStoresIdRoute,
  protecedStoresTopSellRoute: protecedStoresTopSellRoute,
  protecedStoresNewarrivalsRoute: protecedStoresNewarrivalsRoute,
  protecedAboutIndexRoute: protecedAboutIndexRoute,
  protecedMycartIndexRoute: protecedMycartIndexRoute,
  protecedOrdersIndexRoute: protecedOrdersIndexRoute,
  protecedProfileIndexRoute: protecedProfileIndexRoute,
  protecedStoresProductIdRoute: protecedStoresProductIdRoute,
  protecedStoresTypeIdRoute: protecedStoresTypeIdRoute,
}

const protecedRouteRouteWithChildren = protecedRouteRoute._addFileChildren(
  protecedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  protecedRouteRoute: protecedRouteRouteWithChildren,
  loginLoginRoute: loginLoginRoute,
  loginRegisterRoute: loginRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
