/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as protecedRouteRouteImport } from './routes/(proteced)/route'
import { Route as protecedIndexRouteImport } from './routes/(proteced)/index'
import { Route as loginRegisterRouteImport } from './routes/(login)/register'
import { Route as loginLoginRouteImport } from './routes/(login)/login'
import { Route as protecedStoresIndexRouteImport } from './routes/(proteced)/stores/index'
import { Route as protecedOrdersIndexRouteImport } from './routes/(proteced)/orders/index'
import { Route as protecedAboutIndexRouteImport } from './routes/(proteced)/about/index'
import { Route as protecedStoresIdRouteImport } from './routes/(proteced)/stores/$id'
import { Route as protecedStoresProductIdRouteImport } from './routes/(proteced)/stores/product/$id'

const protecedRouteRoute = protecedRouteRouteImport.update({
  id: '/(proteced)',
  getParentRoute: () => rootRouteImport,
} as any)
const protecedIndexRoute = protecedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => protecedRouteRoute,
} as any)
const loginRegisterRoute = loginRegisterRouteImport.update({
  id: '/(login)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const loginLoginRoute = loginLoginRouteImport.update({
  id: '/(login)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const protecedStoresIndexRoute = protecedStoresIndexRouteImport.update({
  id: '/stores/',
  path: '/stores/',
  getParentRoute: () => protecedRouteRoute,
} as any)
const protecedOrdersIndexRoute = protecedOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => protecedRouteRoute,
} as any)
const protecedAboutIndexRoute = protecedAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => protecedRouteRoute,
} as any)
const protecedStoresIdRoute = protecedStoresIdRouteImport.update({
  id: '/stores/$id',
  path: '/stores/$id',
  getParentRoute: () => protecedRouteRoute,
} as any)
const protecedStoresProductIdRoute = protecedStoresProductIdRouteImport.update({
  id: '/stores/product/$id',
  path: '/stores/product/$id',
  getParentRoute: () => protecedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof loginLoginRoute
  '/register': typeof loginRegisterRoute
  '/': typeof protecedIndexRoute
  '/stores/$id': typeof protecedStoresIdRoute
  '/about/': typeof protecedAboutIndexRoute
  '/orders/': typeof protecedOrdersIndexRoute
  '/stores/': typeof protecedStoresIndexRoute
  '/stores/product/$id': typeof protecedStoresProductIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof loginLoginRoute
  '/register': typeof loginRegisterRoute
  '/': typeof protecedIndexRoute
  '/stores/$id': typeof protecedStoresIdRoute
  '/about': typeof protecedAboutIndexRoute
  '/orders': typeof protecedOrdersIndexRoute
  '/stores': typeof protecedStoresIndexRoute
  '/stores/product/$id': typeof protecedStoresProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(proteced)': typeof protecedRouteRouteWithChildren
  '/(login)/login': typeof loginLoginRoute
  '/(login)/register': typeof loginRegisterRoute
  '/(proteced)/': typeof protecedIndexRoute
  '/(proteced)/stores/$id': typeof protecedStoresIdRoute
  '/(proteced)/about/': typeof protecedAboutIndexRoute
  '/(proteced)/orders/': typeof protecedOrdersIndexRoute
  '/(proteced)/stores/': typeof protecedStoresIndexRoute
  '/(proteced)/stores/product/$id': typeof protecedStoresProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/register'
    | '/'
    | '/stores/$id'
    | '/about/'
    | '/orders/'
    | '/stores/'
    | '/stores/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/'
    | '/stores/$id'
    | '/about'
    | '/orders'
    | '/stores'
    | '/stores/product/$id'
  id:
    | '__root__'
    | '/(proteced)'
    | '/(login)/login'
    | '/(login)/register'
    | '/(proteced)/'
    | '/(proteced)/stores/$id'
    | '/(proteced)/about/'
    | '/(proteced)/orders/'
    | '/(proteced)/stores/'
    | '/(proteced)/stores/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  protecedRouteRoute: typeof protecedRouteRouteWithChildren
  loginLoginRoute: typeof loginLoginRoute
  loginRegisterRoute: typeof loginRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(proteced)': {
      id: '/(proteced)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protecedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(proteced)/': {
      id: '/(proteced)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof protecedIndexRouteImport
      parentRoute: typeof protecedRouteRoute
    }
    '/(login)/register': {
      id: '/(login)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof loginRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(login)/login': {
      id: '/(login)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof loginLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(proteced)/stores/': {
      id: '/(proteced)/stores/'
      path: '/stores'
      fullPath: '/stores/'
      preLoaderRoute: typeof protecedStoresIndexRouteImport
      parentRoute: typeof protecedRouteRoute
    }
    '/(proteced)/orders/': {
      id: '/(proteced)/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof protecedOrdersIndexRouteImport
      parentRoute: typeof protecedRouteRoute
    }
    '/(proteced)/about/': {
      id: '/(proteced)/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof protecedAboutIndexRouteImport
      parentRoute: typeof protecedRouteRoute
    }
    '/(proteced)/stores/$id': {
      id: '/(proteced)/stores/$id'
      path: '/stores/$id'
      fullPath: '/stores/$id'
      preLoaderRoute: typeof protecedStoresIdRouteImport
      parentRoute: typeof protecedRouteRoute
    }
    '/(proteced)/stores/product/$id': {
      id: '/(proteced)/stores/product/$id'
      path: '/stores/product/$id'
      fullPath: '/stores/product/$id'
      preLoaderRoute: typeof protecedStoresProductIdRouteImport
      parentRoute: typeof protecedRouteRoute
    }
  }
}

interface protecedRouteRouteChildren {
  protecedIndexRoute: typeof protecedIndexRoute
  protecedStoresIdRoute: typeof protecedStoresIdRoute
  protecedAboutIndexRoute: typeof protecedAboutIndexRoute
  protecedOrdersIndexRoute: typeof protecedOrdersIndexRoute
  protecedStoresIndexRoute: typeof protecedStoresIndexRoute
  protecedStoresProductIdRoute: typeof protecedStoresProductIdRoute
}

const protecedRouteRouteChildren: protecedRouteRouteChildren = {
  protecedIndexRoute: protecedIndexRoute,
  protecedStoresIdRoute: protecedStoresIdRoute,
  protecedAboutIndexRoute: protecedAboutIndexRoute,
  protecedOrdersIndexRoute: protecedOrdersIndexRoute,
  protecedStoresIndexRoute: protecedStoresIndexRoute,
  protecedStoresProductIdRoute: protecedStoresProductIdRoute,
}

const protecedRouteRouteWithChildren = protecedRouteRoute._addFileChildren(
  protecedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  protecedRouteRoute: protecedRouteRouteWithChildren,
  loginLoginRoute: loginLoginRoute,
  loginRegisterRoute: loginRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
